[[detectors]]
name = "AWSKeyDetector"
pattern = "\\bAKIA[0-9A-Z]{16}\\b"
finding_type = "AWS Access Key"
severity = "HIGH"

[[detectors]]
name = "GoogleAPIKeyDetector"
pattern = "\\bAIza[0-9A-Za-z\\-_]{35}\\b"
finding_type = "Google API Key"
severity = "HIGH"

[[detectors]]
name = "SlackTokenDetector"
pattern = "\\bxox[pboa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32}\\b"
finding_type = "Slack Token"
severity = "HIGH"

[[detectors]]
name = "GitHubTokenDetector"
pattern = "\\b(?i)(github|ghp|gho|ghu|ghs)_[0-9a-zA-Z]{36,255}\\b"
finding_type = "GitHub Token"
severity = "HIGH"

[[detectors]]
name = "JWTokenDetector"
pattern = "\\beyJ[A-Za-z0-9-_=]+\\.eyJ[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*\\b"
finding_type = "JWT Token"
severity = "MEDIUM"

[[detectors]]
name = "SSHPrivateKeyDetector"
pattern = "-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----"
finding_type = "SSH Private Key"
severity = "HIGH"

[[detectors]]
name = "PrivateKeyDetector"
pattern = "(?s)-----BEGIN (RSA|DSA|EC|PGP)? PRIVATE KEY-----\\n[\\s\\S]*?-----END (RSA|DSA|EC|PGP)? PRIVATE KEY-----"
finding_type = "Private Key Content"
severity = "HIGH"

[[detectors]]
name = "PasswordDetector"
pattern = "(?i)(password|passwd|pwd)\\s*[:=]\\s*(?-i)[\"']?([^\"'\\n]+)[\"']?"
finding_type = "Password"
severity = "HIGH"

[[detectors]]
name = "EmailDetector"
pattern = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
finding_type = "Email Address"
severity = "LOW"

[[detectors]]
name = "IPAddressDetector"
pattern = "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
finding_type = "IP Address"
severity = "LOW"

[[detectors]]
name = "PhoneNumberDetector"
pattern = "\\b(\\+?1\\s*)?(\\(\\d{3}\\)|\\d{3})[-.\\s]?\\d{3}[-.\\s]?\\d{4}\\b"
finding_type = "Phone Number"
severity = "LOW"

[[detectors]]
name = "CreditCardDetector"
pattern = "\\b(?:\\d[ -]*?){13,16}\\b"
finding_type = "Credit Card Number"
severity = "HIGH"

[[detectors]]
name = "SSNDetector"
pattern = "\\b\\d{3}-\\d{2}-\\d{4}\\b"
finding_type = "Social Security Number"
severity = "HIGH"

[[detectors]]
name = "GenericKeyValueDetector"
pattern = "(?i)(api_?key|secret|password|token|access_?key|security_?key|_key|credential|auth)\\s*[:=]\\s*(?-i)[\"']?([a-zA-Z0-9\\-_=]{10,})[\"']?"
finding_type = "Generic Key/Secret"
severity = "HIGH"

[[detectors]]
name = "CertificateDetector"
pattern = "-----BEGIN CERTIFICATE-----"
finding_type = "Certificate"
severity = "MEDIUM"

[[detectors]]
name = "DatabaseURLDetector"
pattern = "(?i)(mysql|postgres|mongodb|redis)://[^'\"\\s]+@[^'\"\\s]+"
finding_type = "Database URL"
severity = "MEDIUM"

[[detectors]]
name = "Base64Detector"
pattern = "\\b[A-Za-z0-9+/]{20,}[=]{0,2}\\b"
finding_type = "Base64 Encoded String"
severity = "LOW"

[[detectors]]
name = "HighEntropyDetector"
pattern = "\\b[a-f0-9]{32,}\\b|\\b[A-Fa-f0-9]{32,}\\b"
finding_type = "High Entropy String"
severity = "MEDIUM"

[[detectors]]
name = "StripeAPIKeyDetector"
pattern = "\\b(?:sk|pk)_(?:test|live)_[0-9a-zA-Z]{10,}\\b"
finding_type = "Stripe API Key"
severity = "HIGH"

[[detectors]]
name = "AdyenAPIKeyDetector"
pattern = "\\b(?:ws|sk|pk)_[0-9a-zA-Z]{10,}@[a-zA-Z]+\\.[a-zA-Z]+\\b"
finding_type = "Adyen API Key"
severity = "HIGH"

[[detectors]]
name = "PaymentGatewayKeyDetector"
pattern = "\\b(?:api_?key|secret)_(?:test|live)_[0-9a-zA-Z]{10,}\\b"
finding_type = "Generic Payment Gateway Key"
severity = "HIGH"

[[detectors]]
name = "RandomString"
pattern = "\"[a-zA-Z0-9\\-_=]{35,}\""
finding_type = "Random String"
severity = "LOW"

[[detectors]]
name = "FirebaseAPIKeyDetector"
pattern = "AIza[0-9A-Za-z\\-_]{35}"
finding_type = "Firebase API Key"
severity = "HIGH"


[[detectors]]
name = "TwilioAPIKeyDetector"
pattern = "SK[0-9a-fA-F]{32}"
finding_type = "Twilio API Key"
severity = "HIGH"

[[detectors]]
name = "SendGridAPIKeyDetector"
pattern = "SG\\.[A-Za-z0-9]{22}\\.[A-Za-z0-9]{42,43}"
finding_type = "SendGrid API Key"
severity = "HIGH"

[[detectors]]
name = "MailgunAPIKeyDetector"
pattern = "key-[0-9a-zA-Z]{32}"
finding_type = "Mailgun API Key"
severity = "HIGH"

[[detectors]]
name = "DigitalOceanTokenDetector"
pattern = "dop_v1_[a-f0-9]{64}"
finding_type = "DigitalOcean API Token"
severity = "HIGH"

[[detectors]]
name = "HerokuAPIKeyDetector"
pattern = "\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b"
finding_type = "Heroku API Key"
severity = "HIGH"

[[detectors]]
name = "NPMTokenDetector"
pattern = "npm_[0-9a-zA-Z]{36}"
finding_type = "NPM Token"
severity = "HIGH"

[[detectors]]
name = "DiscordTokenDetector"
pattern = "(mfa\\.[0-9a-zA-Z_-]{84}|[\\w-]{24}\\.[\\w-]{6}\\.[\\w-]{27})"
finding_type = "Discord Token"
severity = "HIGH"

[[detectors]]
name = "OpenAIAPIKeyDetector"
pattern = "sk-[0-9a-zA-Z]{48}"
finding_type = "OpenAI API Key"
severity = "HIGH"

[[detectors]]
name = "LinkedInSecretDetector"
pattern = "(?i)[0-9a-z]{16}"
finding_type = "LinkedIn Client Secret"
severity = "HIGH"

[[detectors]]
name = "AzureStorageAccountKeyDetector"
pattern = "DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[^;]+"
finding_type = "Azure Storage Account Key"
severity = "HIGH"

[[detectors]]
name = "MongoDBConnectionStringDetector"
pattern = "mongodb(?:\\+srv)?://[^:]+:[^@]+@[^/]+"
finding_type = "MongoDB Connection String"
severity = "HIGH"

[[detectors]]
name = "CloudinaryURLDetector"
pattern = "cloudinary://[0-9]+:[0-9A-Za-z\\-_]+@[0-9A-Za-z\\-_]+"
finding_type = "Cloudinary URL"
severity = "HIGH"

[[detectors]]
name = "PrivateKeyContentDetector"
pattern = "-----BEGIN RSA PRIVATE KEY-----[\\s\\S]*?-----END RSA PRIVATE KEY-----"
finding_type = "Private Key Content"
severity = "HIGH"

[[detectors]]
name = "DockerHubTokenDetector"
pattern = "dckr_pat_[0-9a-zA-Z_-]{52,56}"
finding_type = "DockerHub Token"
severity = "HIGH"

[[detectors]]
name = "CircleCITokenDetector"
pattern = "CIRCLE_[0-9a-zA-Z_-]{40}"
finding_type = "CircleCI Token"
severity = "HIGH"

[[detectors]]
name = "SquareAccessTokenDetector"
pattern = "sq0atp-[0-9A-Za-z\\-_]{22}"
finding_type = "Square Access Token"
severity = "HIGH"

[[detectors]]
name = "SquareOAuthSecretDetector"
pattern = "sq0csp-[0-9A-Za-z\\-_]{43}"
finding_type = "Square OAuth Secret"
severity = "HIGH"

[[detectors]]
name = "YouTubeAPIKeyDetector"
pattern = "AIza[0-9A-Za-z\\-_]{35}"
finding_type = "YouTube API Key"
severity = "HIGH"

[[detectors]]
name = "GoogleOAuthTokenDetector"
pattern = "ya29\\.[0-9A-Za-z\\-_]+"
finding_type = "Google OAuth Token"
severity = "HIGH"
