import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def write_executable(path: Path, contents: str) -> None:
    path.write_text(contents, encoding="utf-8")
    path.chmod(0o755)


def run_release_scenario(root: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="keywatch-release-") as raw_tmp:
        workspace = Path(raw_tmp)
        tools = workspace / "tools"
        source = workspace / "src"
        tools.mkdir()
        source.mkdir()
        shutil.copy2(root / "scripts" / "release.sh", workspace / "release.sh")
        (workspace / "Cargo.toml").write_text(
            '[package]\nname = "keywatch-release-fixture"\nversion = "1.1.0"\n'
            'edition = "2024"\n',
            encoding="utf-8",
        )
        (workspace / "Cargo.lock").write_text(
            '# This file is automatically @generated by Cargo.\nversion = 4\n\n'
            '[[package]]\nname = "keywatch-release-fixture"\nversion = "1.1.0"\n',
            encoding="utf-8",
        )
        (source / "lib.rs").write_text("", encoding="utf-8")
        (workspace / "CHANGELOG.md").write_text(
            "# Changelog\n\n## [Unreleased]\n\n### Added\n\n- Fixture\n",
            encoding="utf-8",
        )
        (workspace / "action.yml").write_text(
            "inputs:\n  version:\n    description: 'Exact version'\n"
            "    required: false\n    default: '1.1.0'\n",
            encoding="utf-8",
        )
        write_executable(
            tools / "git",
            "#!/usr/bin/env bash\nset -euo pipefail\n"
            "printf '%s\\n' \"$*\" >> \"$GIT_CAPTURE\"\n"
            "case \"${1:-}\" in\n"
            "  rev-parse) printf '%s\\n' master ;;\n"
            "  diff-index) exit 0 ;;\n"
            "  show-ref|ls-remote) exit 1 ;;\n"
            "  *) exit 0 ;;\n"
            "esac\n",
        )
        write_executable(
            tools / "gh",
            "#!/usr/bin/env bash\nif [ \"${1:-}\" = auth ]; then exit 1; fi\nexit 0\n",
        )
        write_executable(
            tools / "cargo",
            "#!/usr/bin/env bash\nset -euo pipefail\n"
            "printf '%s\\n' \"$*\" >> \"$CARGO_CAPTURE\"\n"
            "version=$(sed -n 's/^version = \"\\([^\"]*\\)\"/\\1/p' Cargo.toml)\n"
            "sed -i.bak \"s/^version = \\\"[^\\\"]*\\\"/version = \\\"$version\\\"/\" Cargo.lock\n"
            "rm Cargo.lock.bak\n",
        )
        capture = workspace / "git-capture"
        cargo_capture = workspace / "cargo-capture"
        env = {
            **os.environ,
            "PATH": f"{tools}:{os.environ.get('PATH', '')}",
            "GIT_CAPTURE": str(capture),
            "CARGO_CAPTURE": str(cargo_capture),
        }
        result = subprocess.run(
            ["bash", "release.sh", "create_pr", "2.0.0"],
            check=False,
            cwd=workspace,
            env=env,
            text=True,
            capture_output=True,
        )
        require(result.returncode == 0, f"release scenario failed: {result.stderr!r}")
        action = (workspace / "action.yml").read_text(encoding="utf-8")
        cargo = (workspace / "Cargo.toml").read_text(encoding="utf-8")
        lock = (workspace / "Cargo.lock").read_text(encoding="utf-8")
        changelog = (workspace / "CHANGELOG.md").read_text(encoding="utf-8")
        git_calls = capture.read_text(encoding="utf-8")
        cargo_calls = cargo_capture.read_text(encoding="utf-8")
        require("version = \"2.0.0\"" in cargo, "release must update Cargo.toml")
        require("version = \"2.0.0\"" in lock, "release must update Cargo.lock")
        require("## [2.0.0] -" in changelog, "release must promote the changelog")
        require(
            re.search(r"(?m)^    default: '2\.0\.0'$", action) is not None,
            "release must update the Action version",
        )
        require("add Cargo.toml CHANGELOG.md Cargo.lock action.yml" in git_calls, "release must stage action.yml")
        require("[skip ci]" not in git_calls, "release PR commits must run CI")
        require(cargo_calls == "check --quiet\n", "release must refresh the lockfile without updating dependencies")
