name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: false
        default: "v0.0.0"

permissions:
  contents: write

jobs:
  release:
    name: release-${{ matrix.platform.asset_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: linux
            arch: x86_64

          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: darwin
            arch: x86_64

          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: darwin
            arch: aarch64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: windows
            arch: x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Determine the release version:
      # If triggered by workflow_dispatch then use the input tag,
      # otherwise extract the version from the pushed tag.
      - name: Set Release Version
        id: set-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.tag }}"
          else
            # Remove the leading refs/tags/ from the ref.
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version is ${VERSION}"

      # This step sets up a simpler way to compute the binary name.
      - name: Set Binary Name
        id: set-binary-name
        shell: bash
        run: |
          if [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
            ext=".exe"
          else
            ext=""
          fi
          BINARY_NAME="keywatch-${{ matrix.platform.asset_name }}-${{ matrix.platform.arch }}${ext}"
          echo "BINARY_NAME=${BINARY_NAME}" >> $GITHUB_ENV
          echo "Binary name set to ${BINARY_NAME}"

      # Extract Release Notes only once (on Linux) using the updated AWK script.
      - name: Extract Release Notes
        id: release-notes
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          NOTES=$(awk -v ver="$VERSION" '
            /^## \[/ {
              if (p) { exit }
              # Expecting header format like "## [v1.2.3]"
              if ($2 == "[" ver "]") { p=1; next }
            }
            p { print }
          ' CHANGELOG.md)
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Add aarch64 Apple target
        if: matrix.platform.target == 'aarch64-apple-darwin'
        run: rustup target add aarch64-apple-darwin

      # Build the specific package
      - name: Build Binary
        run: |
          cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare Asset
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.platform.target }}/release/key-watch${{ matrix.platform.os == 'windows-latest' && '.exe' || '' }} \
             release/${BINARY_NAME}

      # Windows: Generate checksum using cmd and Windows syntax.
      - name: Generate SHA-256 (Windows)
        if: matrix.platform.os == 'windows-latest'
        shell: cmd
        run: |
          cd release
          certutil -hashfile %BINARY_NAME% SHA256 | findstr /V "hash" > %BINARY_NAME%.sha256

      # Unix (macOS/Ubuntu): Generate checksum using bash.
      - name: Generate SHA-256 (Unix)
        if: matrix.platform.os != 'windows-latest'
        shell: bash
        run: |
          cd release
          shasum -a 256 "$BINARY_NAME" > "$BINARY_NAME".sha256

      # Create Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "KeyWatch ${VERSION}"
          files: |
            release/${BINARY_NAME}
            release/${BINARY_NAME}.sha256
          body: ${{ steps.release-notes.outputs.NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
